### ISSUE TITLE
Codechef contests not showing up

### ISSUE THREAD

**Issue by raj454raj** [AliOsm/kontests#40]
Can't find any contests in the codechef API - https://kontests.net/api/v1/code_chef

![Screenshot 2021-10-02 at 10 20 01 PM](https://user-images.githubusercontent.com/6368364/135725481-5541ef1b-8138-4e8a-b88f-3cc3d7132771.png)

**Comment by nisarg0** [comment]
Yeah @AliOsm can you please get it working? 
If you don't have time, I will try to make it. But please do reply and tell if you can fix it.

**Comment by AliOsm** [comment]
Hey guys, sorry for being late to reply, always :(

It looks that CodeChef changed their UI, from the logs:

```
2021-11-16T20:15:41.758182+00:00 app[clock.1]: E, [2021-11-16T20:15:41.757974 #4] ERROR -- : no implicit conversion of nil into String (TypeError)
2021-11-16T20:15:41.758204+00:00 app[clock.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/time.rb:372:in `_parse'
2021-11-16T20:15:41.758204+00:00 app[clock.1]: /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/time.rb:372:in `parse'
2021-11-16T20:15:41.758205+00:00 app[clock.1]: /app/app/services/code_chef_service.rb:34:in `extract_contest_info'
2021-11-16T20:15:41.758205+00:00 app[clock.1]: /app/app/services/code_chef_service.rb:19:in `block (2 levels) in create_contests'
2021-11-16T20:15:41.758206+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
2021-11-16T20:15:41.758207+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
2021-11-16T20:15:41.758207+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
2021-11-16T20:15:41.758208+00:00 app[clock.1]: /app/app/services/code_chef_service.rb:18:in `block in create_contests'
2021-11-16T20:15:41.758208+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
2021-11-16T20:15:41.758209+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
2021-11-16T20:15:41.758209+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.11.2-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
2021-11-16T20:15:41.758210+00:00 app[clock.1]: /app/app/services/code_chef_service.rb:15:in `create_contests'
2021-11-16T20:15:41.758210+00:00 app[clock.1]: /app/app/services/site_service.rb:26:in `update_contests'
2021-11-16T20:15:41.758210+00:00 app[clock.1]: /app/config/clock.rb:18:in `block in <module:Clockwork>'
2021-11-16T20:15:41.758211+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/event.rb:54:in `execute'
2021-11-16T20:15:41.758211+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/event.rb:44:in `run'
2021-11-16T20:15:41.758211+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:75:in `block in tick'
2021-11-16T20:15:41.758212+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:73:in `each'
2021-11-16T20:15:41.758212+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:73:in `tick'
2021-11-16T20:15:41.758212+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:64:in `block in run'
2021-11-16T20:15:41.758213+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:63:in `loop'
2021-11-16T20:15:41.758213+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork/manager.rb:63:in `run'
2021-11-16T20:15:41.758214+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/lib/clockwork.rb:46:in `run'
2021-11-16T20:15:41.758214+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/clockwork-1.3.1/bin/clockwork:19:in `<top (required)>'
2021-11-16T20:15:41.758214+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/bin/clockwork:23:in `load'
2021-11-16T20:15:41.758215+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/bin/clockwork:23:in `<top (required)>'
2021-11-16T20:15:41.758215+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
2021-11-16T20:15:41.758215+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
2021-11-16T20:15:41.758215+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
2021-11-16T20:15:41.758216+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
2021-11-16T20:15:41.758216+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2021-11-16T20:15:41.758216+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2021-11-16T20:15:41.758217+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2021-11-16T20:15:41.758217+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
2021-11-16T20:15:41.758218+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2021-11-16T20:15:41.758218+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
2021-11-16T20:15:41.758218+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
2021-11-16T20:15:41.758219+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2021-11-16T20:15:41.758219+00:00 app[clock.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
2021-11-16T20:15:41.758220+00:00 app[clock.1]: /app/bin/bundle:3:in `load'
2021-11-16T20:15:41.758220+00:00 app[clock.1]: /app/bin/bundle:3:in `<main>'
```

Looking into it currently.

**Comment by AliOsm** [comment]
I fixed the issue, you can check the change in this [commit](https://github.com/AliOsm/kontests/commit/52122af91fe7c892afeb5b6853c592cfa87d5a6a).

Basically, I changed CodeChef service to use CodeChef's API instead of crawling the contests from the website using Watir.

Sorry for the late reply.
Keep reporting bugs please ❤️
